name: Update IP Sets and README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run main.go
        run: go run main.go


      - name: Commit and push ipsets to ipsets branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          mv ipsets ../
          git checkout --orphan ipsets-orphan
          git rm -rf .
          git clean -fd
          mv ../ipsets .
          git add -f ipsets
          git commit -m "chore(ipsets): update ipsets" || echo "No changes to commit"
          git push -f origin ipsets-orphan:ipsets

      - name: Commit and push README.md to main branch
        run: |
          git checkout main
          git add README.md
          git commit -m "chore(readme) update" || echo "No changes to commit"
          git push origin main

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          body: "Ciallo～(∠・ω< )⌒★"
          draft: false
          prerelease: false

      - name: Upload Individual Release Assets
        run: |
          for file in ./ipsets/*; do
            asset_name=$(basename "$file")
            gh release upload ${{ steps.date.outputs.date }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}